language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

git:
    submodules: false

before_script:
    - npm install

script:
    - npm run test